"""add is_trashed and trashed_at to notes

Revision ID: bc70fa46cbcc
Revises: ef5d7c1c3089
Create Date: 2026-03-11 17:12:08.456140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc70fa46cbcc'
down_revision = 'ef5d7c1c3089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trashed', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('trashed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('trashed_at')
        batch_op.drop_column('is_trashed')

    # ### end Alembic commands ###
